### ISSUE TITLE
missing script: build

### ISSUE THREAD

**Issue by RajanRV** [leocavalcante/oc-minimal-react#2]
unable to build the react by following commands.
```
sudo npm install
sudo npm run build
```
it shows error  for `sudo npm run build`: 

> npm ERR! missing script: build
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/ccc/.npm/_logs/2019-07-02T12_42_53_395Z-debug.log

and the result of the `sudo npm install` is : 

> core-js@2.6.9 postinstall /opt/lampp/htdocs/octoberReact/themes/leocavalcante-minimal-react/node_modules/babel-runtime/node_modules/core-js
> node scripts/postinstall || echo "ignore"
> 
> Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
> 
> The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 
> 
> Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
> 
> npm WARN minimal-react@1.0.1 No repository field.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 
> added 377 packages from 368 contributors and audited 2829 packages in 9.41s
> found 1 low severity vulnerability
>   run `npm audit fix` to fix them, or `npm audit` for details
>

**Comment by RajanRV** [comment]
This is the log file : 

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
> 2 info using npm@6.9.2
> 3 info using node@v12.5.0
> 4 verbose stack Error: missing script: build
> 4 verbose stack     at run (/usr/lib/node_modules/npm/lib/run-script.js:155:19)
> 4 verbose stack     at /usr/lib/node_modules/npm/lib/run-script.js:63:5
> 4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
> 4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:418:5
> 4 verbose stack     at checkBinReferences_ (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:373:45)
> 4 verbose stack     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:416:3)
> 4 verbose stack     at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
> 4 verbose stack     at ReadFileContext.<anonymous> (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:332:20)
> 4 verbose stack     at ReadFileContext.callback (/usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:90:16)
> 4 verbose stack     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:246:13)
> 5 verbose cwd /opt/lampp/htdocs/octoberReact/themes/leocavalcante-minimal-react
> 6 verbose Linux 4.18.0-25-generic
> 7 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
> 8 verbose node v12.5.0
> 9 verbose npm  v6.9.2
> 10 error missing script: build
> 11 verbose exit [ 1, true ]
>
